name: Publish

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    name: publish-extension
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
      id: node
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install
      run: make install-horusec-vscode
    - name: Lint
      run: make lint-horusec-vscode
    - name: Publish Extension
      uses: lannonbr/vsce-action@master
      with:
        args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
